spring.application.name=publication-service


# Conexión limpia usando el conector de MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/db_listings
spring.datasource.username=root
# Ahora ponemos la contraseña que asignaste en el Paso 1
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de Hibernate segura
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Puerto de escucha del servidor
server.port=8083
#  para que la salida de la consola sea más legible, habilitamos el soporte de colores ANSI
spring.output.ansi.enabled=always