spring.application.name=publication-service

server.port=${SERVER_PORT:}

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&sslMode=trust
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# CORRECCIÓN 1: Desactivar la inicialización por script obligatorio
spring.sql.init.mode=never

# CORRECCIÓN 2: Cambiar de 'update' 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Variables de entorno de AWS
aws.access.key.id=${AWS_ACCESS_KEY_ID}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY}
aws.session.token=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
AWS_S3_BUCKET=${AWS_S3_BUCKET_NAME}


